env:
  desk: 'garden'
  urbit_path: '~/dev/urbit/urbit'
  repo_path: '~/dev/urbit/holium/campfire/'
  ui_path: '~/dev/urbit/holium/campfire/campfire/ui/'
  ship_path: '~/dev/urbit/ships'
script:
  - mount:
    - cmd: 'mount %garden'
      type: 'urbit:app'
  - buildandcopyui:
    - cmd: '~/dev/urbit/holium/campfire/campfire/helpers/build-ui.sh'
      type: 'system'
  - addwavtogarden:
    - cmd: 'cp ~/dev/urbit/holium/campfire/campfire/helpers/wav.hoon ~/dev/urbit/ships/zod/garden/mar/'
      type: 'system'
  - commit:
    - cmd: 'commit %garden'
      type: 'urbit:app'
  - glob:
    - cmd: '-garden!make-glob %garden /ui'
      type: 'urbit:dojo'
